/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_godhuli_rhipe_bridge_REngineCore */

#ifndef _Included_org_godhuli_rhipe_bridge_REngineCore
#define _Included_org_godhuli_rhipe_bridge_REngineCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_godhuli_rhipe_bridge_REngineCore
 * Method:    intializeR
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_godhuli_rhipe_bridge_REngineCore_intializeR
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_godhuli_rhipe_bridge_REngineCore
 * Method:    evalExpression
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_godhuli_rhipe_bridge_REngineCore_evalExpression
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
